const PollData = [
    {
        "question":"Which is the best for front-end?",
        "options":[
            {
                "optionContent":"React JS",
                "optionIndex":"0"
            },
            {
                "optionContent":"Angular JS",
                "optionIndex":"1"
            },
            {
                "optionContent":"Vue JS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
    {
        "question":"Which is the best os?",
        "options":[
            {
                "optionContent":"Windows",
                "optionIndex":"0"
            },
            {
                "optionContent":"Ubuntu",
                "optionIndex":"1"
            },
            {
                "optionContent":"Mac OS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
    {
        "question":"Which is the best for front-end?",
        "options":[
            {
                "optionContent":"React JS",
                "optionIndex":"0"
            },
            {
                "optionContent":"Angular JS",
                "optionIndex":"1"
            },
            {
                "optionContent":"Vue JS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
    {
        "question":"Which is the best os?",
        "options":[
            {
                "optionContent":"Windows",
                "optionIndex":"0"
            },
            {
                "optionContent":"Ubuntu",
                "optionIndex":"1"
            },
            {
                "optionContent":"Mac OS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
    {
        "question":"Which is the best for front-end?",
        "options":[
            {
                "optionContent":"React JS",
                "optionIndex":"0"
            },
            {
                "optionContent":"Angular JS",
                "optionIndex":"1"
            },
            {
                "optionContent":"Vue JS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
    {
        "question":"Which is the best os?",
        "options":[
            {
                "optionContent":"Windows",
                "optionIndex":"0"
            },
            {
                "optionContent":"Ubuntu",
                "optionIndex":"1"
            },
            {
                "optionContent":"Mac OS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
    {
        "question":"Which is the best for front-end?",
        "options":[
            {
                "optionContent":"React JS",
                "optionIndex":"0"
            },
            {
                "optionContent":"Angular JS",
                "optionIndex":"1"
            },
            {
                "optionContent":"Vue JS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
    {
        "question":"Which is the best os?",
        "options":[
            {
                "optionContent":"Windows",
                "optionIndex":"0"
            },
            {
                "optionContent":"Ubuntu",
                "optionIndex":"1"
            },
            {
                "optionContent":"Mac OS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
    {
        "question":"Which is the best for front-end?",
        "options":[
            {
                "optionContent":"React JS",
                "optionIndex":"0"
            },
            {
                "optionContent":"Angular JS",
                "optionIndex":"1"
            },
            {
                "optionContent":"Vue JS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
    {
        "question":"Which is the best os?",
        "options":[
            {
                "optionContent":"Windows",
                "optionIndex":"0"
            },
            {
                "optionContent":"Ubuntu",
                "optionIndex":"1"
            },
            {
                "optionContent":"Mac OS",
                "optionIndex":"2"
            }
        ],
        "votes":[
            {
                "votedBy":"123",
                "option":"1"
            },
            {
                "votedBy":"223",
                "option":"2"
            },
            {
                "votedBy":"124",
                "option":"1"
            },
            {
                "votedBy":"125",
                "option":"1"
            },
            {
                "votedBy":"126",
                "option":"3"
            }
        ],
        "createdBy":"456"
    },
]

export default PollData;